# Generated by Django 3.1.3 on 2021-03-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_something'),
    ]

    operations = [
        migrations.DeleteModel(
            name='something',
        ),
    ]
